[package]
name = "felys-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
felys = "0.1.4"
clap = { version = "4.5.11", features = ["derive"] }
crossterm = "0.28.1"

[[bin]]
name = "felys"
path = "src/main.rs"